Ensure that --dbus-system=filter is used with --trace.
If an application does not have dbus-system filter or sailjail does not
add it following error will be shown with --trace:
    Error: --dbus-system.log requires --dbus-system=filter

Signed-off-by: Jussi Laakkonen <jussi.laakkonen@jolla.com>